service: aws-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}

  environment:
    CONFIG: ${file(config/config.js)}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: '*'

  custom:
    vpc:
      no_vpc:
        securityGroupIds: []
        subnetIds: []
    dynamoTables:
      users: aws-api-users-${self:provider.stage}
    timeout: 10
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceExclude:
        - aws-sdk

package:
  # Pack all functions individually with all necessary dependencies.
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

functions:

  default_authorizer:
    handler: functions/auth/auth.handler
  
  ########################################
  #           USER FUNCTIONS             #
  ########################################
  login:
    handler: functions/users/login.handler
    timeout: ${self:provider.custom.timeout}
    vpc: ${self:provider.custom.vpc.no_vpc}      
    events:
      - http:
          path: /users/login
          method: POST
          cors: true # Default AWS CORS config
  
  list_users:
    handler: functions/users/list.handler
    timeout: ${self:provider.custom.timeout}
    vpc: ${self:provider.custom.vpc.no_vpc} 
    events:
      - http:
          path: /users/list
          method: GET
          cors: true # Default AWS CORS config
          authorizer: default_authorizer

  register_user:
    handler: functions/users/register.handler   
    timeout: ${self:provider.custom.timeout}
    vpc: ${self:provider.custom.vpc.no_vpc} 
    events:
      - http:
          path: /users/register
          method: POST
          cors: true # Default AWS CORS config

  delete_user:
    handler: functions/users/delete.handler
    timeout: ${self:provider.custom.timeout}
    vpc: ${self:provider.custom.vpc.no_vpc}
    events:
      - http:
          path: /users/delete
          method: DELETE
          cors: true # Default AWS CORS config
          authorizer: default_authorizer

  update_user:
    handler: functions/users/update.handler
    timeout: ${self:provider.custom.timeout}
    vpc: ${self:provider.custom.vpc.no_vpc}
    events:
      - http:
          path: /users/update
          method: PUT
          cors: true # Default AWS CORS config
          authorizer: default_authorizer

resources:
  ${file(resources/usersTable.yaml)}
  
